language: python
services:
  - psql
  - mongodb
python:
  - "2.7"
before_install:
  -  sudo apt-get install -y postgresql python-psycopg2 postgresql-contrib mongodb
  -  /usr/lib/postgresql/9.1/bin/createdb FormhubDjangoDB
  -  sudo apt-get install gfortran libatlas-base-dev libjpeg-dev zlib1g-dev
  -  sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so ~/virtualenv/python2.7/lib/
  -  sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/
install:
  - pip install numpy --use-mirrors
  - pip install -r requirements.pip
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
script:
  - python manage.py test --noinput --settings=formhub.preset.travis_test
  - ./js_tests/EnvJasmine/bin/run_all_tests.sh --testDir=../ --configFile=../env_jasmine.conf.js
notifications:
    irc: "irc.freenode.org#sel-columbia"
